### ISSUE TITLE
Implement abstract functions in components

### ISSUE THREAD

**Issue by saket** [evant/kotlin-inject#165]
Can `kotlin-inject` implement abstract functions in components, just the way how abstract values are implemented? I wanna expose some factory lambdas from my component but using them as vals is a bit inconvenient from usage sites because kotlin doesn't allow named arguments for lambdas.

Here's what I'm currently doing:

```kotlin
@Component
abstract class SomeComponent) {
  protected abstract val presenterFactory: (navigator: Navigator) -> SomePresenter

  fun presenter(navigator: Navigator): SomePresenter {
    return presenterFactory(navigator)
  }
}
```

can this be reduced to:

```kotlin
@Component
abstract class SomeComponent) {
  abstract fun presenter(navigator: Navigator): SomePresenter
}
```

**Comment by evant** [comment]
This was considered but not implemented for a couple reasons:
1. This solves the case in generated provides methods but do not for `@Inject` constructors and `@Provides` methods, i.e. you still would have to do:
```kotlin
@Inject class Foo(presenterFactory: (navigator: Navigator) -> SomePresenter)
```
or
```kotlin
@Provides
fun provideFoo(presenterFactory: (navigator: Navigator) -> SomePresenter): Foo = ...
```
I'd argue these cases would be far more common than the ultimate provides methods so it seems weird to optimize for the less common case.

2. It's expected that when using assisted injection you'd have few arguments, so the limitation that you can't used named args in lambda shouldn't be a big deal. (Though I do wish kotlin supported named args in lambdas).

Therefore ended up with keeping things consistent instead of implementation a special-case here, yeah the recommended pattern is to to:

```kotlin
@Component
abstract class SomeComponent) {
  abstract val presenter: (navigator: Navigator) -> SomePresenter
}
...
val presenter = component.presenter(navigator)
```

Just a thought, you can create a factory class to get named args, this is similar to the helper fun you have but can be used in all locations. Not sure this is worth it though.

```kotlin
@Inject class SomePresenterFactory(private val presenter: (Navigator) -> SomePresenter) {
    operator fun invoke(navigator: Navigator): SomePresenter = presenter(navigator)
}
```

**Comment by saket** [comment]
All fair points. Exposing a factory class is a neat idea. Let me try using that!

**Comment by evant** [comment]
Just had a thought, maybe we could treat [fun interfaces](https://kotlinlang.org/docs/fun-interfaces.html) the same we do lambda functions, this would allow named params when injecting. It does bring up the same explicitness questions as https://github.com/evant/kotlin-inject/issues/164 but I think it's worth playing around with.
