### ISSUE TITLE
Allow recusive dependencies with lazy/functions

### ISSUE THREAD

**Issue by evant** [evant/kotlin-inject#19]
Right now this stackoverflows but it should be able to be resolved:

```kotlin
class LazyCycleFoo(val bar: LazyCycleBar)
class LazyCycleBar(val foo: Lazy<LazyCycleFoo>)

@Component abstract class LazyCycleComponent {
    abstract val bar: LazyCycleBar

    @Provides fun bar(foo: Lazy<LazyCycleFoo>) = LazyCycleBar(foo)

    @Provides fun foo(bar: LazyCycleBar) = LazyCycleFoo(bar)
}
```

should generate:
```kotlin
class InjectLazyCycleComponent : LazyCycleComponent() {
    override val bar: LazyCycleBar
        get() {
            lateinit var bar: LazyCycleBar
            return bar(lazy { foo(bar) }).also { bar = it }
        }
}
```

**Comment by japplin** [comment]
Wouldn't this be a duplicate binding error?

**Comment by evant** [comment]
No, each type is only provided once. Since I added cycle detection the above probably errors as a cycle instead of stack overflowing. Actually on the fence in supporting this as it's easy to get a runtime error if you don't delay construction, but for what it's worth dagger does support this pattern.

**Comment by japplin** [comment]
> No, each type is only provided once. Since I added cycle detection the above probably errors as a cycle instead of stack overflowing. Actually on the fence in supporting this as it's easy to get a runtime error if you don't delay construction, but for what it's worth dagger does support this pattern.

Sorry you're right, I misread the snippet. I think this feature makes sense to have.

**Comment by markus2610** [comment]
LateInit does not work with scope.

<img width="812" alt="Bildschirmfoto 2023-06-08 um 21 11 15" src="https://github.com/evant/kotlin-inject/assets/726806/80460944-ffff-4ce7-9bf8-64977b1648bf">

**Comment by evant** [comment]
@markus2610 could you file a new bug?

**Comment by markus2610** [comment]
I have it. I've created a Repository with two branches.

In this example, the field  bar is imported as an abstract read-only property

[LazyCycleComponent](https://github.com/markus2610/LateInitScope/blob/main/app/src/main/java/de/mw/lateinitscope/LazyCycleComponent.kt#L12)

then the implementation in InjectApplicationComponent is generated and the scope works

[InjectApplicationComponent](https://github.com/markus2610/LateInitScope/blob/main/generated/ksp/debug/kotlin/de/mw/lateinitscope/inject/InjectApplicationComponent.kt)

otherwise the implementation in InjectMainActivityComponent is generated  and the scope does not work

[InjectMainActivityComponent](https://github.com/markus2610/LateInitScope/blob/ScopeMissing/generated/ksp/debug/kotlin/de/mw/lateinitscope/main/InjectMainActivityComponent.kt)

A hint for recusive dependencies with lazy/functions with scope is helpful.
A generated implementation in a component that depends on an implementation in another component with scope needs an abstract read-only property in that component, otherwise the scope will not work.
