### ISSUE TITLE
Allow use of `fun interface` for assisted injection 

### ISSUE THREAD

**Issue by dellisd** [evant/kotlin-inject#243]
Maybe this is too dagger-like, but since `fun interface`s are functionally equivalent to a functional type it should be technically possible to allow them for assisted injection.

The main benefit is that it allows a `Factory` type to be nested within your injectable class, which isn't possible with a typealias.

e.g. 
```kotlin
@Inject class MyClass(
  private val paramA: ClassA,
  private val paramB: ClassB,
) {
  fun interface Factory {
    fun create(paramB: ClassB): MyClass
  }
}

// Usage elsewhere
@Inject class MyConsumer(
  private val myClassFactory: MyClass.Factory,
)
```

**Comment by IlyaGulya** [comment]
This would be pretty awesome, since lambdas are quite limited (parameter names are not mandatory and you can't call it with parameter names specified on call site)

**Comment by sergeshustoff** [comment]
@evant is there any way we can help with getting that to release?

**Comment by evant** [comment]
There's https://github.com/evant/kotlin-inject/pull/341 that's been hanging out for a while now that I haven't had a chance to look at too closely, would be a good starting point.

At a high level, I think function injection & assisted injection should be looked at together with this feature as they have the same limitations. Need to sure we have an api that makes sense for both.

**Comment by evant** [comment]
Hey! I've been thinking about how to support factory interfaces as an alternative to lambdas for assisted injection (there's already a couple of pr's up about it) and I think I've come down to 2 potential designs with some pros & cons and would love some feedback.

**1. require a dedicated annotation**
```kotlin
@Inject class MyType(dep: Dep, @Assisted arg: String)

@InjectFactory interface MyFactory {
    fun create(arg: String): MyType
}
```
pros:
- very explicit
- supports default params

cons:
- requires a new annotation
- inconsistent with lambdas/typealiass which don't require an annotation

**2. only support fun interface**
```kotlin
@Inject class MyType(dep: Dep, @Assisted arg: String)

fun interface MyFactory {
    fun create(arg: String): MyType
}
```
pros:
- kotlin compiler enforces the single fun requirement so we don't have to
- more closely mirrors lambdas

cons:
- potentially less clear that the factory can be used for injection
- does not support default params 

I want to also bring up how this may play with function injection which has some discussion started in https://github.com/evant/kotlin-inject/issues/252. **To be clear I'm more interested in deciding between the 2 options above**, but providing this for additional context.

Right now function injection 'magically' matches the name of a typealias to the function name to connect one, which is not super obvious, and requires some odd limitations like they must be declared in the same file. Whiles it's possible to bring that behavior over to the factory interfaces as well, it may be a good idea for this feature to have an explicit annotation connecting the two.

```kotlin
@InjectFunction("myFunction") typealias MyFunction = (String) -> MyType

@InjectFunction("myFunction") fun interface CreateMyFunction {
    fun create(arg: String): MyType
}

@Inject
fun myFunction(dep: Dep, @Assisted arg: String): MyType { ... }
```

But going with option 1 would require both annotations which may make it less clear how these features should interact.
```kotlin
@InjectFactory
@InjectFunction("myFunction")
fun interface CreateMyFunction {
    fun create(arg: String): MyType
}
```

Alternatively, the other issue linked combines these though I'm not sure they should be because they _feel_ like distinct features?
```kotlin
@InjectFactory(functionName = "myFunction")
fun interface CreateMyFunction {
    fun create(arg: String): MyType
}
```

**Comment by eygraber** [comment]
My knee jerk reaction is to say `#2` to avoid a new annotation, but maybe being more explicit is the better approach? Tough decision, I'm still pulled in both directions.

**Comment by sergeshustoff** [comment]
Not having annotation for fun interface feels ambiguous... Maybe it's an assisted factory, maybe it's just an interface that supposed to have a bound implementation, maybe it was expected to be provided from somewhere. In case of any error it would be extra tough for user to understand what is wrong if our error says that we can't construct something inside factory when in fact it wasn't intended as a factory at all. It's a weird corner case and I doubt anyone would use fun interfaces like that, but...

**Comment by evant** [comment]
Those concerns are exactly why a bare interface is not one of the options I'm proposing. My thought is usages of fun interfaces are equivalent enough to lambdas that it doesn't become an issue. For example, they are designed to make creating an instance on the fly easier which doesn't really make sense for a bound implementaion. But you are right that I am assuming people use them in a certain way which could cause problems if it's incorrect in practice.

**Comment by dave08** [comment]
Maybe not as nice, but much more explicit would be to have a property in the annotation on the class being assisted:

```kotlin
@Inject(withAssisted = MyFactory::class) class MyType(dep: Dep, @Assisted arg: String)

interface MyFactory {
    fun create(arg: String): MyType
}
```
then one very clearly sees what's being used to inject what.

**Comment by ZacSweers** [comment]
I prefer the explicitness of option 1. Option 2 feels too much in the realm of "just because we can do it doesn't mean we should". Option 2 also prohibits default functions, which are fairly common in dagger's assisted factories. Sure, one could require use of extension functions instead, but at the same time why limit it?
