### ISSUE TITLE
Support factory interfaces for function injection

### ISSUE THREAD

**Issue by evant** [evant/kotlin-inject#252]
Function injection is a useful feature especially with [compose](https://developer.android.com/jetpack/compose). However, because it only works with function types you lose support for named & optional arguments which can make the signature harder to read. The proposed solution is to also support factory interfaces which support these features.

Currently you can do:
```kotlin
typealias MyFunction = (String) -> String

@Inject
fun MyFunction(dep: Dep, @Assisted arg: String): String = ...
```

In addition you should be able to do:
```kotlin
interface MyFunction {
  operator fun invoke(arg: String = "default"): String
}

@Inject
fun MyFunction(dep: Dep, @Assisted arg: String): String = ...
```

which can be called as:
```kotlin
MyFunction()
MyFunction(arg = "value")
```

Alternative:

Since we know which arguments are assisted we could in theory generate this factory function ourselves. However due to processing limitations they wouldn't be able to support default arguments. It would also mean more generated code exposed throughout the codebase which it limited to `MyComponent::create` currently. For these reasons I propose going with the more verbose version above. This may be re-visited if/when we get a way to read default arguments.

**Comment by sergeshustoff** [comment]
Disclaimer: I seem to be failing to see the usecase for function injection. It's likely that I miss something
But in case I'm not missing something there here is my case for deprecating the whole thing)

I see a bunch of problems with function injection in general:
- typealias is required for function to be discoverable by DI, but it generally feels off and when function is renamed the typealias is not (though the matching name is required)
- typealias goes against #253 in a way that it is kind of a qualifier for the function while we can't do that for classes anymore. So api get's inconsistent here. I know, it's far fetched as typealias here is not exactly that, but still.
- in a way typealias does for a function what `@Provides` binding does for a class, but it's external to the component.
- seems that it breaks when 2 different types of magic mix in #388 (compose and kotlin-inject). While it is a bug in ksp I'd expect similar problems not to be uncommon simply because mixing magic like that is dangerous.
- in case of receiverFun from test it looks like receiver works as an assisted parameter, but it's not (and can't be) marked like that.
    
        typealias receiverFun = String.(arg: NamedFoo) -> String
        
        @Inject
        fun String.receiverFun(dep: Foo, @Assisted arg: NamedFoo): String = this
    
And then wrapping the function in a class with inject constructor doesn't look like much more code while makes it much more understandable and clear. Plus this way there is no need for the assisted injection (in this case):

    @Inject
    class ReceiverFuner(private val dep: Foo) {
        fun receiverFun(usedToBeAReceiver: String, arg: NamedFoo): String = usedToBeAReceiver
    }

This approach doesn't work well for receiver though... But is it a common case?

So, with this in mind, maybe it's worth considering deprecating it away and making api simpler? It's not my lib and it's totally up to you what features you want in it. And, again, maybe I'm not seeing some vital usecase for the function injection

**Comment by evant** [comment]
> Disclaimer: I seem to be failing to see the usecase for function injection. It's likely that I'm missing something

I can talk about how I'm using it currently with compose.

My app architecture consists of 'Repositories', 'Controllers', and 'Pages'. For this discussion you can think of a 'Controller' as equivalent to a 'ViewModel'. Each page is top-level composable function that injects a controller factory, and takes the current page's arguments.

```kotlin
typealias MyPage = @Composable (Page.MyPage, Modifier) -> Unit

@Composible
fun MyPage(createMyController: CreateMyController, @Assisted page: Page.MyPage, @Assisted modifier: Modifier) {
   ...
}
```

You are correct this would be equivalent to doing
```kotlin
@Inject
class MyPage(private val createMyController: CreateMyController) {
    @Composible
    @SuppressLint("ComposeNamingUppercase")
    operator fun invoke(page: Page.MyPage, modifier: Modifier) {
        ...
    }
}
```
and I've considered moving to that pattern multiple times. But it feels weird, a `@Composible` is normally a top-level function and if I were to write things manually without an injection lib that is how I would do it.

> typealias goes against https://github.com/evant/kotlin-inject/issues/253

Not really, it ends up working far more like other cases of assisted injection where it's the function type that's actually used and not the name. Compare:
```kotlin
typealias CreateFoo = (B) -> Foo
@Inject
class Foo(val a: A, @Assisted val b: B)
```
to
```kotlin
typealias CreateFoo = (A) -> Foo
@Inject
fun CreateFoo(a: A, @Assisted b: B) : Foo
```
the one difference is the name is special for it to match the function (have more thoughts on that further down)

> in case of receiverFun from test it looks like receiver works as an assisted parameter, but it's not (and can't be) marked like that.

You are right, this is a weird wart, thanks for bringing it up. It looks like receivers were not properly considered when the `@Assisted` annotation was introduced. You can't mark a receiver as `@Assisted` on a `@Provides` function either and I think that goes in the other direction (it can only be injected).

> This approach doesn't work well for receiver though... But is it a common case?

I don't know, I'm not using a receiver on an injected function in my project for one data-point.

> the interface is bound to the function only by the matching name. Not by returning said function like it would a class or by an annotation explicitly referencing the function. That kind of indirect connection feels wrong as an API.

I do agree with that btw, the reason the existing api came about is because there is no way to reference a function in an annotation. I have considered requiring something like `@FunctionInjection("receiverFun")` but I'm not sure if that's actually better?

**Comment by sergeshustoff** [comment]
Ok, I see. I guess I'll try to look at function references in annotations or something like that to maybe use for linking interfaces or typealiases to a function...

> But it feels weird, a `@Composible` is normally a top-level function and if I were to write things manually without an injection lib that is how I would do it.

After splitting a huge project into modules I ended up with interfaces with composable functions implemented in different modules a few times (yes, it's weird) and stopped feeling like compose functions are special and necessarily top level. The system ones are, but they're just building blocks. Plus look at [Voyager](https://github.com/adrielcafe/voyager?tab=readme-ov-file#------------voyager-compose-on-warp-speed) - it uses composable function in 'screen" class.

Plus with interface as proposed above there would be composable inside it.

**Comment by sergeshustoff** [comment]
Btw 

    typealias CreateFoo = (A) -> Foo
     @Inject
     fun CreateFoo(a: A, @Assisted b: B) : Foo

This looks like CreateFoo behaves more like something that `@Provides` then something with things injected in it...

**Comment by evant** [comment]
> This looks like CreateFoo behaves more like something that `@Provides`

Not quite, you can only inject the function, not it's return value

**Comment by sergeshustoff** [comment]
In this case looks more like you can inject assisted factory for return type that's guaranteed to use the function under the hood. Still achievable with `@Provides`, though might require qualifier on return type and would not be linked that explicitly to the provider function as it is now

**Comment by sergeshustoff** [comment]
Ok, so looks like we want to keep this api as is. So here is my proposal how to do it with assisted factory:

    @Target(CLASS, TYPEALIAS)
    annotation class InjectFunction(
        /**
         * Optional name of the injected function. Just name if it's in te same package, full package otherwise. Name of annotated interface or typealias is used otherwise
         */
        val funName: String = ""
    )
    
    @InjectFunction("someMagic")
    typealias SomeMagic1 = (NamedFoo) -> String
    // or
    @InjectFunction("someMagic")
    fun interface SomeMagic2 {
        operator fun invoke(arg: NamedFoo): String
    }

    fun someMagic(foo: Foo, @Assisted arg: NamedFoo): String = arg.name

Why I suggest an additional annotation: both typealias and interface look and feel too much like assisted injection while it's not that strictly speaking. Because with assisted injection logic is based on what is returned and here logic is based on specific function with the same name. 
fun someMagic does not contribute to dependency graph except for specific cases when typealias is used, and unlike assisted injection we can't just use (NamedFoo) -> String in random place and expect it to be resolved using someMagic function. 
Another option would be to reverse the link and annotate the function instead, but I'd rather have annotation on typealias/interface because this way we can also have `@AssistedFactory` annotation for assisted factories (both typealias and interface). This way the 2 cases are separated, yet similar enough.

Does this make sense?

**Comment by sergeshustoff** [comment]
> Not quite, you can only inject the function, not it's return value

Btw I still can't quite understand what 'injecting a function' means. We don't get that exact function as a result as opposed to injecting into class constructor. Similarity to `provides` is still there - in both cases the annotated function is called inside generated code and in both cases we call a function with a fewer params (generated wrapper function that calls annotated one). And in both cases the only similarity between annotated and called function is the return type and the assisted parameters if any (besides matching names in case of function injection)

**Comment by evant** [comment]
👍 That general approach sounds good, will have to think about the naming
> Another option would be to reverse the link and annotate the function instead

This is actually not possible, the processor follows types from the component that was annotated so any metadata has to be on that type. The current implementation 'cheats' a little and looks for the same name in the current file but having something more explicit here would remove that limitation.

**Comment by sergeshustoff** [comment]
I wander if it's worth trying to support multiple functions in a single assisted factory... On one hand it looks weird, on the other hand it kinda allows a weird composition instead of inheritance in a complex multi-module app (when scoped by lifecycle and not by feature).

The case in a multi-module app currently I'd do something like this:

    interface FeatureAComponent {
        fun depA(): DepA1
        val assistedThingA: (name: String) -> DepA2
    }

    interface FeatureABindings {
        @Provides
        val SomethingAImpl.bind(): SomethingA = this
    }

    interface FeatureBComponent {
        fun depB(): DepB1
        val assistedThingB: (name: String) -> DepB2
    }

    @Component
    abstract class Component : FeatureAComponent, FeatureBComponent, FeatureABindings

But if assisted factory wasn't an assisted factory and supported multiple functions I could do something like this:

    @PartialComponent
    interface FeatureAComponent {
        fun depA(): DepA1
        fun assistedThingA(name: String): DepA2
    }

    interface FeatureABindings {
        @Provides
        val SomethingAImpl.bind(): SomethingA = this
    }

    @PartialComponent
    interface FeatureBComponent {
        fun depB(): DepB1
        fun assistedThingB(name: String): DepB2
    }

    @Component
    abstract class Component : FeatureABindings {
        abstract val featureA: FeatureAComponent
        abstract val featureB: FeatureBComponent
    }
    
In this case an assisted factory would be a particular case of partial component. And any functions of partial component would be implemented just as if thery were functions of component itself (except without problems with clashing names). Plus in incorporates #261. Plus it's a single interface to cover a lot of functionality. There are cons too though - a bit complicated to understand, function reference for function injection needs to move to some other annotation the will be put on a function in component/partial component or on a typealias.

**Comment by evant** [comment]
Your ranting does make sense. What you came up with looks suspiciously similar to dagger's [subcomponents](https://dagger.dev/dev-guide/subcomponents). I had originally chosen not to implement that feature because choosing between subcomponents and component dependencies was always a source of confusion in dagger that I wanted to avoid.

**Comment by sergeshustoff** [comment]
Huh. I didn't think of this similarity. With that in mind supporting such 'almost subconponents' seems a slippery slope
