### ISSUE TITLE
Direct users to use the generated classes instead.

### ISSUE THREAD

**Issue by efemoney** [evant/kotlin-inject#266]
I'm not sure why creating a (possibly unnecessary) `KClass` is the recommended pattern but I think it'll be better to direct users to use the the `Inject**Component()` constructors instead of `**Component::class.create()`

There's is also no difference in terms of devX, as the `create()` fun being auto generated will not be available on failures just as much as the generated `Inject**Component` class.

**Comment by evant** [comment]
It's for encapsulation. the `create()` method returns the type `MyComponent` instead of `InjectMyComponent`, this prevents you to reaching into implementation details of that inject class that aren't guaranteed  to be stable.

**Comment by PaulWoitaschek** [comment]
If it's only for encapsulation we could also make the generated component internal and only generate a top level function

```kotlin
public fun MyComponent(): MyComponent = InjectMyComponent()
```

That would allow us to get rid of both the `create` on KClass, as well as the companion one. And would make using the library a nuance easier as there is now only one way to do things.

**Comment by efemoney** [comment]
Yeah exactly @PaulWoitaschek. Generate a "constructor function" instead.

**Comment by evant** [comment]
:thinking: That's not a bad idea. The one downside I'd see is the error message would be more confusing if the generator fails to run (complaining about not being allowed to construct an abstract class instead of a missing method) but maybe it's worth it.

**Comment by eygraber** [comment]
> public fun MyComponent(): MyComponent = InjectMyComponent()

Did a quick spike on this and it seems like it'll cause problems with conflicting overloads between the generated factory function and the `MyComponent` constructor (which is weird because I feel like I've done this before with no issues, but it makes sense that it wouldn't work).

**Comment by eygraber** [comment]
[Here's the spike in case anyone is interested](https://github.com/eygraber/kotlin-inject/commit/4a7a9dc757fd1e6691a66489ba66007bc09c4937)

**Comment by evant** [comment]
Ah yep you are right, here's a very simple example:
```kotlin
abstract class MyClass
fun MyClass(): MyClass = TODO()
```

```
Conflicting overloads: public fun MyClass(): MyClass defined in com.example in file MyClass.kt, public constructor MyClass() defined in com.example.MyClass
```

> which is weird because I feel like I've done this before with no issues

I bet the arguments where different, seems the only conflict when the signatures match. Unfortunately, that will almost always be the case here.

**Comment by evant** [comment]
Ok got it to work by doing the following, I do worry this is too hacky to be workable through?

```kotlin
// needs protected to ensure callers can't call it (leads to it being preferred over the function)
abstract class MyClass protected constructor(arg: String)

// By adding a default arg to the end it appeases the conflicting overloads check
fun MyClass(arg: String, ignore: Nothing? = null): MyClass = TODO()
```

**Comment by eygraber** [comment]
I think it's a hard ask to have consumers add `protected constructor` to everything. 

I wonder if `invoke` would work?

**Comment by evant** [comment]
unfortunately not, kotlin will always prefer the constructor to the function if it's accessible

**Comment by evant** [comment]
Hm, we could name the function differently, which ends up being closer to the original proposal here. (would require a rename of the generated class for the same reasons as before but I think that's workable)

```kotlin
class InjectMyComponentImpl(arg: String) : MyComponent(arg) { ... }

fun InjectMyComponent(arg: String): MyComponent = InjectMyComponentImpl(arg)
```

**Comment by eygraber** [comment]
Going back to the original ask:

> I'm not sure why creating a (possibly unnecessary) KClass is the recommended pattern

Since you're going to be accessing an instance of that class, I'm pretty sure the `KClass` is going to be created anyways (if it isn't already)

In terms of devX, while `InjectMyComponent()` looks better than `MyComponent::class.create()`, neither are particularly discoverable without knowing about them. `KClass` gets points for being better for cmd-click as @evant mentioned.

I imagine the consensus is that the `Companion` approach would be best, but it comes with the requirement for a `Companion` to be explicitly defined. Personally I'd say make that the default / only approach, because there's clear remediation in the error (which ironically also makes it discoverable). Definitely would be super annoying to foist onto anyone not using it (and not sure where that falls on the semver scale, although kotlin-inject is still pre 1.0.0...).

[statics](https://github.com/Kotlin/KEEP/blob/statics/proposals/statics.md) would probably be the best path forward, but there's no timeline there, and no way of knowing what the ABI compat would be for someone who is already using the `Companion` approach.

**Comment by evant** [comment]
> I imagine the consensus is that the Companion approach would be best, but it comes with the requirement for a Companion to be explicitly defined
[statics](https://github.com/Kotlin/KEEP/blob/statics/proposals/statics.md) would probably be the best path forward, but there's no timeline there, and no way of knowing what the ABI compat would be for someone who is already using the Companion approach.

Yep, that direction was the original plan. It's under a flag right now because of the companion declaration requirement and the likely abi change when statics becomes a thing. The idea is at that point it will be moved to the recommended (and eventually only) approach.

I think I'm going to go ahead and close this, while the proposal here was reasonable, language limitations mean I think it's better to stick with the current course.

**Comment by evant** [comment]
In terms of changing the default _now_ eh, it's really six of one, half a dozen of the other. Each have their warts and each will need to be migrated eventually. I don't think there's a strong enough reason to swap. It also makes that eventual migration fairly simple because either:

1. You don't have the companion flag enabled, you get deprecation warnings on your `create` calls with an autofix, or
2. You have the flag enabled, you get a warning it's now deprecated and you can remove any companion declarations that are now not being used.
